apiVersion: skaffold/v4beta5
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: yemelia/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: yemelia/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: yemelia/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: yemelia/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: yemelia/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: yemelia/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'